- name: create local folders for persistent volumes
  file:
    path: "{{ item.local_path }}"
    state: "{{ 'directory' if action == 'install' else 'absent' }}"
  loop: "{{ helper_volumes }}"
  become: true
  when: not cluster_in_docker

- name: "create persistent volume yaml"
  local_action:
    module: kubernetes.core.k8s
    state: "{{ 'present' if action == 'install' else 'absent' }}"
    template: "pvc.yaml"
  run_once: True
