version: '3'
services:

  k3s-master:
    image: "rancher/k3s:{{ k3s_version }}"
    # hostname: k3s-master
    container_name: k3s-master
    command: >-
      server
      --disable servicelb
      --disable traefik
      --disable local-storage
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_TOKEN={{ k3s_token }}
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - k3s-server:/var/lib/rancher/k3s
{% for volume in helper_volumes %}
    - {{ volume.name }}:{{ volume.local_path }}
{% endfor %}
    # This is just so that we get the kubeconfig file out
    - .:/output
    ports:
    - 6443:6443

  k3s-worker:
    deploy:
      replicas: 0
    image: "rancher/k3s:{{ k3s_version }}"
    tmpfs:
    - /run
    - /var/run
    privileged: true
    environment:
    - K3S_URL=https://k3s-master:6443
    - K3S_TOKEN={{ k3s_token }}

volumes:
  k3s-server: {}
{% for volume in helper_volumes %}
  {{ volume.name }}: {}
{% endfor %}