- name: k8s
  description: enable features required to run k8s in a container
  config:
    boot.autostart: "true"
    linux.kernel_modules: ip_vs,ip_vs_rr,ip_vs_wrr,ip_vs_sh,ip_tables,ip6_tables,netlink_diag,nf_nat,overlay,br_netfilter
    raw.lxc: |
      lxc.apparmor.profile=unconfined
      lxc.mount.auto=proc:rw sys:rw cgroup:rw
      lxc.cgroup.devices.allow=a
      lxc.cap.drop=
    security.nesting: "true"
    security.privileged: "true"
  devices:
    aadisable:
      path: /sys/module/nf_conntrack/parameters/hashsize
      source: /sys/module/nf_conntrack/parameters/hashsize
      type: disk
    aadisable1:
      path: /sys/module/apparmor/parameters/enabled
      source: /dev/null
      type: disk
    aadisable2:
      path: /dev/kmsg
      source: /dev/kmsg
      type: disk
    aadisable3:
      path: /sys/fs/bpf
      source: /sys/fs/bpf
      type: disk
- name: user
  description: add user
  config:
    user.user-data: |
      #cloud-config
      users:
        - name: root
          plain_text_passwd: bagabu
          ssh_authorized_keys: {{ ssh_public_key }}
